CREATE DATABASE  IF NOT EXISTS `linuxfr_rails` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `linuxfr_rails`;

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

/*!40000 ALTER TABLE `friendly_id_slugs` DISABLE KEYS */;
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (3,'section-1',1,1,'Section',NULL,'2012-11-08 05:54:21');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (4,'section-2',2,1,'Section',NULL,'2012-11-08 05:54:30');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (5,'section-3',3,1,'Section',NULL,'2012-11-08 05:54:39');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (6,'section-4',4,1,'Section',NULL,'2012-11-08 05:54:48');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (7,'linux',5,1,'Section',NULL,'2012-11-08 06:15:15');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (8,'atelier-formation-gnu-linux-objectif-l-autonomie-a-paris-le-24-11',1,1,'News',NULL,'2012-11-08 06:18:14');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (9,'jacob-kaplan-moss-ecrire-une-bonne-documentation',1,1,'Diary',NULL,'2012-11-08 06:23:45');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (10,'top500-92-4-des-supercalculateurs-tournent-sous-linux',2,1,'Diary',NULL,'2012-11-08 06:25:45');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (11,'clang-day-pour-freebsd',3,1,'Diary',NULL,'2012-11-08 06:27:52');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (12,'the-linux-foundation-hp-obtient-un-nouveau-rang',4,1,'Diary',NULL,'2012-11-08 06:30:26');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (13,'thttpgpd-ou-comment-openudc-a-ressuscite-le-bon-vieux-thttpd',5,1,'Diary',NULL,'2012-11-08 06:35:51');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (14,'tiling-interne-ou-externe-telle-est-la-question',6,1,'Diary',NULL,'2012-11-08 06:59:37');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (15,'effedsfdsf',7,1,'Diary',NULL,'2012-11-14 05:48:18');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (16,'tetrtretre-retre',8,1,'Diary',NULL,'2012-11-14 06:51:30');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (17,'sfddfsdf',9,1,'Diary',NULL,'2012-11-14 06:54:17');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (18,'dssd-dssd',10,1,'Diary',NULL,'2012-11-14 07:02:51');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (19,'dssd-dssd--2',11,1,'Diary',NULL,'2012-11-14 07:03:49');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (20,'zed',5,1,'User',NULL,'2012-11-14 07:04:41');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (21,'fqsfqfqfsdfq',12,1,'Diary',NULL,'2012-11-14 07:05:26');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (22,'rezrezrzerez',13,1,'Diary',NULL,'2012-11-14 07:05:59');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (23,'acceleration-ssd-sous-linux',14,1,'Diary',NULL,'2012-11-16 06:45:41');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (24,'le-domaine-public-est-du-communisme-pour-nicolas-seydoux',15,1,'Diary',NULL,'2012-11-16 06:47:12');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (25,'pour-l-emploi-d-un-vocabulaire-correct',16,1,'Diary',NULL,'2012-11-16 06:48:07');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (26,'l-evolution-touche-t-il-a-sa-fin',17,1,'Diary',NULL,'2012-11-16 06:49:03');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (27,'pourquoi-les-differentes-versions-de-debian-sont-nommees-d-apres-des-personnage-de-toy-s-story',18,1,'Diary',NULL,'2012-11-16 06:50:18');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (28,'enfin-une-distribution-linux-qui-me-convient',19,1,'Diary',NULL,'2012-11-16 06:51:24');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (29,'iran-une-longueur-d-avance-sur-la-france',20,1,'Diary',NULL,'2012-11-16 06:52:08');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (30,'avec-un-bon-dell-on-peut',21,1,'Diary',NULL,'2012-11-16 06:53:05');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (31,'rohm-aquafairy',22,1,'Diary',NULL,'2012-11-16 06:54:12');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (32,'newton-adventure-la-soluce-6-6-bonus',23,1,'Diary',NULL,'2012-11-16 06:55:19');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (33,'newton-adventure-la-soluce-6-6-bonus--2',24,1,'Diary',NULL,'2012-11-16 07:52:06');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (34,'kded-appmenu-le-retour',25,1,'Diary',NULL,'2012-11-16 14:05:27');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (35,'open-data-pour-open-cities-le-challenge-innovation',26,1,'Diary',NULL,'2012-11-16 14:07:51');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (36,'google-entreprise-vertueuse',27,1,'Diary',NULL,'2012-11-16 14:09:03');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (37,'php-a-fractal-of-bad-design',28,1,'Diary',NULL,'2012-11-16 14:10:34');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (38,'facebook-remplace-html5-par-du-natif-dans-ses-applications-smartphone',29,1,'Diary',NULL,'2012-11-16 14:11:52');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (39,'general-cherche-materiel',1,1,'Forum',NULL,'2012-11-19 05:33:17');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (40,'general-petites-annonces',2,1,'Forum',NULL,'2012-11-19 05:33:54');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (41,'linux-noyau',3,1,'Forum',NULL,'2012-11-19 05:34:15');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (42,'linux-livecd',4,1,'Forum',NULL,'2012-11-19 05:34:37');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (43,'programmation-java',5,1,'Forum',NULL,'2012-11-19 05:35:01');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (44,'programmation-sql',6,1,'Forum',NULL,'2012-11-19 05:35:18');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (45,'choix-d-un-netbook',1,1,'Post',NULL,'2012-11-19 05:36:59');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (46,'nouveau-portable-bis',2,1,'Post',NULL,'2012-11-19 05:37:42');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (47,'cherche-disque-dur-ssd-capacite-250go',3,1,'Post',NULL,'2012-11-19 05:38:13');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (48,'donne-tour-pc-gateway-700-en-etat-de-marche',4,1,'Post',NULL,'2012-11-19 05:39:10');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (49,'comment-connaitre-l-origine-d-un-kernel-panic-depuis-le-mode-graphique',5,1,'Post',NULL,'2012-11-19 05:40:15');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (50,'mises-a-jours-bios-pour-windows-8-benefiquent-a-linux',6,1,'Post',NULL,'2012-11-19 05:40:45');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (51,'besoin-du-live-cd',7,1,'Post',NULL,'2012-11-19 05:41:31');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (52,'bonne-distro-recovery-en-francais',8,1,'Post',NULL,'2012-11-19 05:41:59');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (53,'didjix-ou-mixxx-propulse-par-archlinux',9,1,'Post',NULL,'2012-11-19 05:42:33');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (54,'java-jar-application-web-agpl-et-itext',10,1,'Post',NULL,'2012-11-19 05:43:25');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (55,'platefrome-anonymisatrice',11,1,'Post',NULL,'2012-11-19 05:44:06');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (56,'fichiers-csv',12,1,'Post',NULL,'2012-11-19 05:44:32');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (57,'calcul-sur-plusieurs-aggregats',13,1,'Post',NULL,'2012-11-19 05:51:58');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (58,'performances-de-join-exists-sur-postgres',14,1,'Post',NULL,'2012-11-19 05:55:31');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (59,'sum-sur-une-colonne-float-mysql',15,1,'Post',NULL,'2012-11-19 05:55:54');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (60,'replication-de-base-mysql',16,1,'Post',NULL,'2012-11-19 05:56:18');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (61,'le-libre-et-mon-activite',1,1,'Poll',NULL,'2012-11-19 06:19:13');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (62,'vers-quelle-partie-du-site-linuxfr-org-allez-vous-en-premier',2,1,'Poll',NULL,'2012-11-19 06:21:31');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (63,'la-tribune-de-l-espace-de-redaction-affiche-le-nom-d-utilisateur-et-non-le-pseudo',1,1,'Tracker',NULL,'2012-11-19 06:27:53');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (64,'gestion-des-pages-supprimees-du-wiki',2,1,'Tracker',NULL,'2012-11-19 06:28:18');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (65,'les-urls-ipv6-ne-sont-pas-supportees',3,1,'Tracker',NULL,'2012-11-19 06:29:36');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (66,'indiquer-la-licence-du-contenu-dans-les-flux-atom-concernes',4,1,'Tracker',NULL,'2012-11-19 06:30:06');
INSERT INTO `friendly_id_slugs` (`id`, `slug`, `sluggable_id`, `sequence`, `sluggable_type`, `scope`, `created_at`) VALUES (67,'detournement-des-liens-page-perso',5,1,'Tracker',NULL,'2012-11-19 06:30:44');
/*!40000 ALTER TABLE `friendly_id_slugs` ENABLE KEYS */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

